permissions:
  actions: read
  contents: read
  security-events: write
  id-token: write  # Required for private repositories and OIDC authentication
  packages: read   # Needed if using private CodeQL packs
